### ISSUE TITLE
TimeMachine implementation details

### ISSUE THREAD

**Issue by robertmircea** [LMAX-Exchange/Simple-DSL#6]
Can you give a little more insight on implementation details for methods handling time machine? Specifically, I am interested in createTimePoint(), waitUntil(), enableTimeMachine() but others are welcomed.

How do you "virtualize" time more exactly?

**Comment by ajsutton** [comment]
There's some detail about how the time machine works at https://www.symphonious.net/2014/04/01/testinglmax-time-travel-and-the-tardis/

In terms of createTimePoint, it's relatively simple - it's ultimately just assigning a time point a name so we can use it more meaningfully. Because our time machine can only go forward in time, the times we use in ATs must be dynamic so we use time values like "<now>" or "<now> plus 3 hours".  To get to relatively fixed points in time we can also say things like "<next midnight>", "<next weekday>" or "<next monday>". I'm not entirely sure why we wound up putting <> around some bits of our time definitions, I suspect it was easier to make the rather horrible regex that does the parsing work that way.  From those anchor points we can then plus/minus x days/hours/minutes etc.

More recently we've found that tests often want to run at a specific time of day so we've added the ability to say "<next monday> at 15:00".
